name: Build Android & iOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-android:
    name: 🟩 Build Android
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js (for React Native or similar)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install npm dependencies
        run: npm install

      # 4. Setup Java 17 explicitly (fixes JDK path issue)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      # 5. Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # 6. Verify Java setup (debug info)
      - name: Verify Java setup
        run: |
          java -version
          echo "JAVA_HOME is set to: $JAVA_HOME"

      # 7. Grant Gradle wrapper permissions
      - name: Grant permission to Gradlew
        run: chmod +x android/gradlew

      # 8. Build Android Debug APK
      - name: Build Android Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      # 9. Upload APK artifact
      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

  build-ios:
    name: 🍎 Build iOS
    runs-on: macos-latest
    needs: build-android

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Install dependencies
      - name: Install npm dependencies
        run: npm install

      # 4. Install CocoaPods dependencies
      - name: Install CocoaPods
        working-directory: ios
        run: pod install --repo-update

      # 5. Build iOS Debug target
      - name: Build iOS Debug
        working-directory: ios
        run: |
          xcodebuild \
            -workspace YourApp.xcworkspace \
            -scheme YourApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build

      # 6. Upload build logs (useful for debugging CI builds)
      - name: Upload iOS build logs
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-logs
          path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Build/*.xcactivitylog
