name: Build Android & iOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-android:
    name: 🟩 Build Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm install

      - name: Setup Java & Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant permission to Gradlew
        run: chmod +x android/gradlew

      - name: Build Android Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk

  build-ios:
    name: 🍎 Build iOS
    runs-on: macos-latest
    needs: build-android

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm install

      - name: Install CocoaPods
        working-directory: ios
        run: pod install --repo-update

      - name: Build iOS Debug
        working-directory: ios
        run: |
          xcodebuild \
            -workspace YourApp.xcworkspace \
            -scheme YourApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build

      - name: Upload iOS build logs
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-logs
          path: ~/Library/Developer/Xcode/DerivedData/**/Logs/Build/*.xcactivitylog
